### ISSUE TITLE
Add website license

### ISSUE THREAD

**Issue by nemobis** [dialect-app/website#1]
Hello! The website is currently proprietary, with no license defined and a footer stating
> © 2020–2023 The Dialect Authors

The application itself uses GPL so it would make sense to pick a copyleft Creative Commons license, i.e. CC BY-SA 4.0. At least the license should be stated in this repository but ideally also in the footer, see [CC marking instructions](https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license) if your website generator/theme doesn't support it.

I see so far @rafaelmardojai is the only contributor so he can/needs to perform/approve the relicensing.

**Comment by rafaelmardojai** [comment]
Thanks,

I have licensed the website code as MIT and the contents as CC BY-SA 4.0.
