### ISSUE TITLE
LibreTranslate instance not reachable

### ISSUE THREAD

**Issue by heldderarbeit** [dialect-app/website#6]
Not sure if this already on the radar, but I noticed the service on https://lt.dialectapp.org/ is not available.

![Screenshot From 2024-11-12 18-28-08](https://github.com/user-attachments/assets/0ab569a9-244c-4d5e-9794-3c49d8668798)

![image](https://github.com/user-attachments/assets/1782662d-f367-4e4c-be8e-6e03aae9e27a)

**Comment by rafaelmardojai** [comment]
Thanks! The service should be back now.
